create database pi_teste4
go
use pi_teste4

--Feita
CREATE TABLE CURSO(
COD_CURSO INT IDENTITY PRIMARY KEY,
NOME_CURSO VARCHAR (20) NOT NULL)

--Feita
CREATE TABLE DISCIPLINA(
COD_DISCIPLINA INT IDENTITY PRIMARY KEY,
NOME_DISCIPLINA VARCHAR (30))

--Feita
CREATE TABLE CURRICULO(
COD_CURRICULO INT IDENTITY PRIMARY KEY,
SEMESTRE_GRADE INT NOT NULL,
COD_DISCIPLINA INT NOT NULL REFERENCES DISCIPLINA, 
COD_CURSO INT NOT NULL REFERENCES CURSO)
 
--Feita
CREATE TABLE PROFESSOR(
MATRICULA_PROFESSOR INT IDENTITY PRIMARY KEY,
NOME_PROFESSOR VARCHAR (100) NOT NULL)

--Feita
CREATE TABLE TURMA(
COD_TURMA INT IDENTITY PRIMARY KEY, 
COD_CURRICULO INT NOT NULL REFERENCES CURRICULO,
MATRICULA_PROFESSOR INT NOT NULL REFERENCES PROFESSOR,
SEMESTRE INT NOT NULL,
ANO INT NOT NULL)

/*CREATE TABLE TURMA (
    COD_TURMA INT IDENTITY PRIMARY KEY, 
    COD_CURRICULO INT NOT NULL REFERENCES CURRICULO,
    MATRICULA_PROFESSOR INT NOT NULL,
    SEMESTRE INT NOT NULL,
    ANO INT NOT NULL,
    CONSTRAINT FK_TURMA_MATRICULA_PROFESSOR
        FOREIGN KEY (MATRICULA_PROFESSOR)
        REFERENCES PROFESSOR(MATRICULA_PROFESSOR)
        ON DELETE CASCADE
);*/

--Feita
CREATE TABLE SECRETARIA(
MATRICULA_SECRETARIA INT IDENTITY PRIMARY KEY,
NOME_SECRETARIA VARCHAR (100) NOT NULL)

--Feita
CREATE TABLE SALA(
COD_SALA INT IDENTITY PRIMARY KEY,
TIPO VARCHAR (15) NOT NULL, 
CAPACIDADE INT NOT NULL)

--Feita
CREATE TABLE AGENDA(
COD_AGENDA INT IDENTITY PRIMARY KEY,
DATA_AGENDADA DATE NOT NULL,
HORA TIME NOT NULL)

--Feita
CREATE TABLE AGENDA_SALA(
COD_AGENDA_SALA INT IDENTITY PRIMARY KEY,
STATUS VARCHAR (10) NOT NULL DEFAULT 'disponível',
COD_SALA INT NOT NULL REFERENCES SALA,
COD_AGENDA INT NOT NULL REFERENCES AGENDA)

--Feita
CREATE TABLE RESERVA(
COD_RESERVA INT IDENTITY PRIMARY KEY,
COD_AGENDA_SALA INT NOT NULL REFERENCES AGENDA_SALA ON DELETE CASCADE,
COD_TURMA INT REFERENCES TURMA,
MATRICULA_SECRETARIA INT NOT NULL REFERENCES SECRETARIA,
MANUTENCAO BIT NOT NULL)

------------------------------
INSERT INTO CURSO (NOME_CURSO) VALUES ('Engenharia');
INSERT INTO CURSO (NOME_CURSO) VALUES ('Matemática');
INSERT INTO CURSO (NOME_CURSO) VALUES ('Computação');
select * from CURSO

INSERT INTO DISCIPLINA (NOME_DISCIPLINA) VALUES ('Cálculo');
INSERT INTO DISCIPLINA (NOME_DISCIPLINA) VALUES ('Física');
INSERT INTO DISCIPLINA (NOME_DISCIPLINA) VALUES ('Programação');
select * from DISCIPLINA

INSERT INTO CURRICULO (SEMESTRE_GRADE, COD_DISCIPLINA, COD_CURSO) VALUES (1, 1, 1);
INSERT INTO CURRICULO (SEMESTRE_GRADE, COD_DISCIPLINA, COD_CURSO) VALUES (2, 2, 1);
INSERT INTO CURRICULO (SEMESTRE_GRADE, COD_DISCIPLINA, COD_CURSO) VALUES (1, 3, 2);
select * from CURRICULO

INSERT INTO PROFESSOR (NOME_PROFESSOR) VALUES ('Dr. José Silva');
INSERT INTO PROFESSOR (NOME_PROFESSOR) VALUES ('Dra. Maria Souza');
INSERT INTO PROFESSOR (NOME_PROFESSOR) VALUES ('Dr. Paulo Ribeiro');
INSERT INTO PROFESSOR (NOME_PROFESSOR) VALUES ('Dr. Carlos Oliveira');
INSERT INTO PROFESSOR (NOME_PROFESSOR) VALUES ('Dr. Amanda Santos');
select * from PROFESSOR

INSERT INTO TURMA (COD_CURRICULO, MATRICULA_PROFESSOR, SEMESTRE, ANO) VALUES (1, 1, 1, 2023);
INSERT INTO TURMA (COD_CURRICULO, MATRICULA_PROFESSOR, SEMESTRE, ANO) VALUES (2, 2, 2, 2023);
INSERT INTO TURMA (COD_CURRICULO, MATRICULA_PROFESSOR, SEMESTRE, ANO) VALUES (3, 3, 1, 2023);
INSERT INTO TURMA (COD_CURRICULO, MATRICULA_PROFESSOR, SEMESTRE, ANO) VALUES (1, 4, 2, 2024);
INSERT INTO TURMA (COD_CURRICULO, MATRICULA_PROFESSOR, SEMESTRE, ANO) VALUES (2, 5, 1, 2024);
select * from turma

INSERT INTO SECRETARIA (NOME_SECRETARIA) VALUES ('Ana Mendes');
INSERT INTO SECRETARIA (NOME_SECRETARIA) VALUES ('Carlos Ferreira');
INSERT INTO SECRETARIA (NOME_SECRETARIA) VALUES ('Luciana Barbosa');
INSERT INTO SECRETARIA (NOME_SECRETARIA) VALUES ('João Silva');
INSERT INTO SECRETARIA (NOME_SECRETARIA) VALUES ('Patrícia Costa');
select * from SECRETARIA

INSERT INTO SALA (TIPO, CAPACIDADE) VALUES ('Laboratório', 30);
INSERT INTO SALA (TIPO, CAPACIDADE) VALUES ('Auditório', 100);
INSERT INTO SALA (TIPO, CAPACIDADE) VALUES ('Sala de Aula', 40);
INSERT INTO SALA (TIPO, CAPACIDADE) VALUES ('Laboratório', 25);
INSERT INTO SALA (TIPO, CAPACIDADE) VALUES ('Sala de Aula', 60);
select * from sala

INSERT INTO AGENDA (DATA_AGENDADA, HORA) VALUES ('2023-10-05', '08:00:00');
INSERT INTO AGENDA (DATA_AGENDADA, HORA) VALUES ('2023-10-06', '10:00:00');
INSERT INTO AGENDA (DATA_AGENDADA, HORA) VALUES ('2023-10-07', '14:00:00');
INSERT INTO AGENDA (DATA_AGENDADA, HORA) VALUES ('2023-10-08', '09:00:00');
INSERT INTO AGENDA (DATA_AGENDADA, HORA) VALUES ('2023-10-09', '15:00:00');
select * from AGENDA

INSERT INTO AGENDA_SALA (STATUS, COD_SALA, COD_AGENDA) VALUES ('Reservado', 1, 1);
INSERT INTO AGENDA_SALA (STATUS, COD_SALA, COD_AGENDA) VALUES ('Disponível', 2, 2);
INSERT INTO AGENDA_SALA (STATUS, COD_SALA, COD_AGENDA) VALUES ('Reservado', 3, 3);
INSERT INTO AGENDA_SALA (STATUS, COD_SALA, COD_AGENDA) VALUES ('Disponível', 4, 4);
INSERT INTO AGENDA_SALA (STATUS, COD_SALA, COD_AGENDA) VALUES ('Reservado', 5, 5);
select * from AGENDA_SALA

INSERT INTO RESERVA (COD_AGENDA_SALA, COD_TURMA, MATRICULA_SECRETARIA, MANUTENCAO) VALUES (1, 1, 1, 0);
INSERT INTO RESERVA (COD_AGENDA_SALA, COD_TURMA, MATRICULA_SECRETARIA, MANUTENCAO) VALUES (2, 2, 2, 1);
INSERT INTO RESERVA (COD_AGENDA_SALA, COD_TURMA, MATRICULA_SECRETARIA, MANUTENCAO) VALUES (3, 3, 3, 0);
INSERT INTO RESERVA (COD_AGENDA_SALA, COD_TURMA, MATRICULA_SECRETARIA, MANUTENCAO) VALUES (4, 4, 4, 0);
INSERT INTO RESERVA (COD_AGENDA_SALA, COD_TURMA, MATRICULA_SECRETARIA, MANUTENCAO) VALUES (5, 5, 5, 1);
select * from RESERVA

select * from AGENDA_SALA

delete from reserva where COD_AGENDA_SALA = 3
select * from PROFESSOR
select * from turma

--não deleta pq usa na turma
delete from PROFESSOR where MATRICULA_PROFESSOR = 2 
